### ISSUE TITLE
regression in login

### ISSUE THREAD

**Issue by ilarimikkonen** [Profirator/Profi-platform#15]
disable native login with Admin user (fiware login only option)
logout
login with FIWARE user

Expected: user logs in.

Actual: "login forbidden" message is displayed

when restoring the native login this works. THis is a SHOW STOPPER for 0.60.1 release.

**Comment by ilarimikkonen** [comment]
tested with 0.60.1 - build from dev branch

**Comment by Peteri1111** [comment]
https://github.com/Profirator/Profi-platform/commit/bcff3374da4e6802259b26cbd187f63cc6a83a1d

**Comment by ilarimikkonen** [comment]
problem with the current way is that it checks from settingsa when logging in. you can only create settings when logged in.

```
> use apinfdb2
switched to db apinfdb2
> db.Settings.findOne()
null
```

**Comment by ilarimikkonen** [comment]
user is created when signing up so checking if there is no users is not an answer.
