### ISSUE TITLE
if you give wrong password, token successfully fetched message is shown

### ISSUE THREAD

**Issue by ilarimikkonen** [Profirator/Profi-platform#4]
![image](https://user-images.githubusercontent.com/7221736/81150422-8b15b000-8f88-11ea-9abc-892c36d35a5d.png)

to reproduce:
- go to platfrom with FIWARE login
- get an Oauth token with wrong pass
Expected:
- error message is shown
Actual:
- "we have successfully got you a token"

**Comment by matleppa** [comment]
Response structure to Oauth-token request has changes thus causing, that the script can not distinguish the responses in cases a) the Oauth token was gotten correctly and b) password was erroneous. 
The response examination in script must be updated correspondingly.
